sudo: false
language: python

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -r -f $HOME/.cache/pip/log

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - '3.5-dev'
  - nightly
  - pypy
  - pypy3

env:
  - TOX_ENV=py INSTALL_EXTRAS=''
  - TOX_ENV=py INSTALL_EXTRAS='[jwt]'

matrix:
  include:
    - python: pypy
      env: TOX_ENV=pypy PYPY_VERSION='4.0.0'
    - python: pypy
      env: TOX_ENV=pypy PYPY_VERSION='4.0.0' INSTALL_EXTRAS='[jwt]'
    - python: 2.7
      env: TOX_ENV=pep8
    - python: 2.7
      env: TOX_ENV=pep8 INSTALL_EXTRAS='[all]'
    - python: 2.7
      env: TOX_ENV=pylint
    - python: 2.7
      env: TOX_ENV=pylint INSTALL_EXTRAS='[all]'
    - python: 2.7
      env: TOX_ENV=coverage
    - python: 2.7
      env: TOX_ENV=coverage INSTALL_EXTRAS='[all]'
    - python: 3.5
      env: TOX_ENV=pep8
    - python: 3.5
      env: TOX_ENV=pep8 INSTALL_EXTRAS='[all]'
    - python: 3.5
      env: TOX_ENV=pylint
    - python: 3.5
      env: TOX_ENV=pylint INSTALL_EXTRAS='[all]'
    - python: 3.5
      env: TOX_ENV=coverage
    - python: 3.5
      env: TOX_ENV=coverage INSTALL_EXTRAS='[all]'

# commands to install dependencies
install:
  - ./.travis/install.sh
# commands to run
script:
  - ./.travis/run.sh
after_success:
  - if [ "-x$TOX_ENV" = "xcoverage" ]; then coveralls; fi
